### ISSUE TITLE
[KeePassXC] SecretService backend doesn't work as expected

### ISSUE THREAD

**Issue by andreystepanov** [jaraco/keyring#589]
**Describe the bug**
I'm trying to get rid of `gnome-keyring` in favor of KeePassXC's SecretService integration and encountered some issues while configuring `protonvpn-cli` which uses `keyring`.

Not being a Python developer, i tried to debug the issue anyway.

As of now, i can confirm that `secretstorage` itself successfully executes `collection.create_item` function and item shows up in KeePassXC. 

`keyring`, on the other hand, returns an error:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/python/keyring/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/home/user/python/keyring/keyring/backends/SecretService.py", line 92, in set_password
    collection.create_item(label, attributes, password, replace=True)
  File "/nix/store/av09888lb2i48lc510b5hpxwc2961zhm-python3.10-secretstorage-3.3.2/lib/python3.10/site-packages/secretstorage/collection.py", line 125, in create_item
    return Item(self.connection, new_item, self.session)
  File "/nix/store/av09888lb2i48lc510b5hpxwc2961zhm-python3.10-secretstorage-3.3.2/lib/python3.10/site-packages/secretstorage/item.py", line 31, in __init__
    self._item.get_property('Label')
  File "/nix/store/av09888lb2i48lc510b5hpxwc2961zhm-python3.10-secretstorage-3.3.2/lib/python3.10/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/nix/store/av09888lb2i48lc510b5hpxwc2961zhm-python3.10-secretstorage-3.3.2/lib/python3.10/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownInterface] ("No such interface 'org.freedesktop.DBus.Properties' at object path '/'",)
```

So it cannot `collection.create_item`, but it still can retrieve one no problem using `collection.search_items`.

**To Reproduce**
1. Configure KeePassXC SecretService integration
2. Execute `keyring set service username`

**Expected behavior**
New entry should be successfully created in keyring.

**Environment**

- OS: NixOS

```
$ keyring --list-backends
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: -1)
```

**Comment by mitya57** [comment]
Please try SecretStorage 3.3.3, which was released yesterday. I believe it should fix the issue.

**Comment by andreystepanov** [comment]
@mitya57 I've seen https://github.com/mitya57/secretstorage/issues/39, but it didn't fix my issue.

Error changed though:

```shell
Traceback (most recent call last):
  File "/nix/store/ffgirbdfwwx8ccq8ghf22x01i2089b03-protonvpn-cli-3.12.0/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 73, in login
    self.protonvpn.login(username, password)
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 36, in login
    self._env.api_session.authenticate(username, password, human_verification)
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
    result = self._func(session, *args, **kwargs)
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 394, in authenticate
    ExecutionEnvironment().keyring[
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 107, in __setitem__
    raise exceptions.KeyringError(e)
protonvpn_nm_lib.exceptions.KeyringError: [org.freedesktop.DBus.Error.UnknownObject] ("No such object path '/org/freedesktop/secrets/aliases/default'",)
```

I don't think that issue is on `secretstorage` side though. 
As i've mentioned above, using `secretstorage` on itself works fine. But when API is used from `keyring` something goes wrong.

Any ideas?

**Comment by mitya57** [comment]
When you use SecretStorage on itself, do you use `get_default_collection()` or `get_any_collection()`?

**Comment by andreystepanov** [comment]
In order to uderstand what causes trouble i tried to test `secretstorage` directly in the repl.

```python
>>> import secretstorage
>>> connection = secretstorage.dbus_init()
>>> collection = secretstorage.get_default_collection(connection)
>>> attributes = {'application': 'myapp', 'another attribute': 'test'}
>>> item = collection.create_item('My first item', attributes, b'pass', replace=True)
```

No problem here.
But testing in the repl with `keyring` causes error.

Now tried `get_any_collection` and it also works just fine.

**Comment by mitya57** [comment]
Does it work if you use keyring library, but outside of protonvpn application?
```
>>> import keyring.backends.SecretService
>>> k = keyring.backends.SecretService.Keyring()
>>> k.set_password('foo', 'bar', 'pass')
>>> k.get_password('foo', 'bar')
```

Also, can you share the full traceback from your error, including lines before “During handling of the above exception, another exception occurred”?

**Comment by andreystepanov** [comment]
Just to make it clear, i did test it outside `protonvpn` package before i opened an issue.
Exactly the way you suggested.

Here's another try:

```python
>>> import keyring.backends.SecretService
>>> k = keyring.backends.SecretService.Keyring()
>>> k.set_password('foo', 'bar', 'pass')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/python/keyring/keyring/backends/SecretService.py", line 92, in set_password
    collection.create_item(label, attributes, password, replace=True)
  File "/nix/store/av09888lb2i48lc510b5hpxwc2961zhm-python3.10-secretstorage-3.3.2/lib/python3.10/site-packages/secretstorage/collection.py", line 125, in create_item
    return Item(self.connection, new_item, self.session)
  File "/nix/store/av09888lb2i48lc510b5hpxwc2961zhm-python3.10-secretstorage-3.3.2/lib/python3.10/site-packages/secretstorage/item.py", line 31, in __init__
    self._item.get_property('Label')
  File "/nix/store/av09888lb2i48lc510b5hpxwc2961zhm-python3.10-secretstorage-3.3.2/lib/python3.10/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/nix/store/av09888lb2i48lc510b5hpxwc2961zhm-python3.10-secretstorage-3.3.2/lib/python3.10/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownInterface] ("No such interface 'org.freedesktop.DBus.Properties' at object path '/'",)
>>>
```
In this particular case i'm still using `3.3.2 version of `secretstorage` but it doesn't change the outcome anyway.

> Also, can you share the full traceback from your error, including lines before “During handling of the above exception, another exception occurred”?

```
-------------------------------------------------

-----------	Initialized protonvpn-cli	-----------

-------------------------------------------------
2022-08-14 12:20:23,640 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
2022-08-14 12:20:23,641 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='login', version=False, help=False, get_logs=False)
2022-08-14 12:20:59,820 — cli_wrapper.py — INFO — login:68 — Credentials provided, attempting to login
2022-08-14 12:21:02,006 — cli_wrapper.py — ERROR — login:117 — [org.freedesktop.DBus.Error.UnknownObject] ("No such object path '/org/freedesktop/secrets/aliases/default'",)
Traceback (most recent call last):
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 92, in __setitem__
    self.__keyring_backend.set_password(
  File "/nix/store/jisjzfqn4r7cvbfzmv67hpbxmx85rk25-python3.10-keyring-23.6.0/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 87, in set_password
    collection = self.get_preferred_collection()
  File "/nix/store/jisjzfqn4r7cvbfzmv67hpbxmx85rk25-python3.10-keyring-23.6.0/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/nix/store/wgmj5ii126lh31yx36w6p07aq07x8slj-python3.10-secretstorage-3.3.3/lib/python3.10/site-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
  File "/nix/store/wgmj5ii126lh31yx36w6p07aq07x8slj-python3.10-secretstorage-3.3.3/lib/python3.10/site-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/nix/store/wgmj5ii126lh31yx36w6p07aq07x8slj-python3.10-secretstorage-3.3.3/lib/python3.10/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/nix/store/wgmj5ii126lh31yx36w6p07aq07x8slj-python3.10-secretstorage-3.3.3/lib/python3.10/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownObject] ("No such object path '/org/freedesktop/secrets/aliases/default'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/ffgirbdfwwx8ccq8ghf22x01i2089b03-protonvpn-cli-3.12.0/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 73, in login
    self.protonvpn.login(username, password)
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 36, in login
    self._env.api_session.authenticate(username, password, human_verification)
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
    result = self._func(session, *args, **kwargs)
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 394, in authenticate
    ExecutionEnvironment().keyring[
  File "/nix/store/lifiv9wfxx57fvdnqzz5ag2g6sfrf5md-python3.10-protonvpn-nm-lib-3.10.0/lib/python3.10/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 107, in __setitem__
    raise exceptions.KeyringError(e)
protonvpn_nm_lib.exceptions.KeyringError: [org.freedesktop.DBus.Error.UnknownObject] ("No such object path '/org/freedesktop/secrets/aliases/default'",)

```

**Comment by andreystepanov** [comment]
Holly molly, it worked :)

I have updated `secretstorage` to `3.3.3` and now it works from `keyring` side as well!
@mitya57 Thanks, you've saved me at least couple days, that's for sure ;)

Will override `protonvpn` to work with never version and report back.

**Comment by andreystepanov** [comment]
Alright, now everything works great from `protonvpn` side as well.

**Comment by andreystepanov** [comment]
Just for those who also on NixOS, here's how i fixed it by just overriding dependencies:

```nix
{ lib, python3, fetchFromGitHub, dialog }:

let
  python = python3.override {
    packageOverrides = self: super: {
      secretstorage = super.secretstorage.overridePythonAttrs (oldAttrs: rec {
        version = "3.3.3";
        src = oldAttrs.src.override {
          inherit version;
          hash = "sha256-JANTPvNp7KbSuoFxhXbF4PVk1cyhtY9zqLI+fU7uvXc=";
        };
      });
      keyring = super.keyring.overridePythonAttrs (oldAttrs: rec {
        version = "23.8.2";
        src = oldAttrs.src.override {
          inherit version;
          hash = "sha256-DZlz+IkYUPGt5fJqr9BrsWhl+7rj/Faw3vtqFKJiQAM=";
        };
      });
    };
  };
in with python.pkgs;
buildPythonApplication rec {
  pname = "protonvpn-cli";
  version = "3.12.0";
  format = "setuptools";

  disabled = pythonOlder "3.5";

  src = fetchFromGitHub {
    owner = "protonvpn";
    repo = "linux-cli";
    rev = version;
    sha256 = "sha256-z0ewAqf8hjyExqBN8KBsDwJ+SA/pIBYZhKtXF9M65HE=";
  };

  propagatedBuildInputs = [ protonvpn-nm-lib pythondialog dialog ];

  # Project has a dummy test
  doCheck = false;

  meta = with lib; {
    description = "Linux command-line client for ProtonVPN";
    homepage = "https://github.com/protonvpn/linux-cli";
    maintainers = with maintainers; [ wolfangaukang ];
    license = licenses.gpl3Plus;
    platforms = platforms.linux;
    mainProgram = "protonvpn-cli";
  };
}
```
